version: '3.8'
services:
  ollama_context:
    image: ollama/ollama:latest
    ports:
      - 2207:11434
    volumes:
      - ./code:/code
      - ../models/ollama/models:/root/.ollama
    container_name: ollama_context
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

  ollama-webui:
    # image: ghcr.io/open-webui/open-webui:main
    image: ghcr.io/open-webui/open-webui:latest
    container_name: ollama-webui
    volumes:
      - ./ollama-webui:/app/backend/data
    depends_on:
      - ollama_context
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama_context:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Test AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=testing
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    # restart: unless-stopped
    restart: always
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
  
